spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/simple-bi
    username: simplebi
    password:
    sql-script-encoding: UTF-8
    initialization-mode: embedded

  # h2 connected console when using
  h2:
    console:
      enabled: true

server:
  port: 8000
