spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/simple-bi
    username: simplebi
    password:
    sql-script-encoding: UTF-8
    initialization-mode: embedded
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # h2 connected console when using
  h2:
    console:
      enabled: true

server:
  port: 8000

simple-bi:
  file-upload-path: ~/simple-bi
  secret-key: simple-bi
